spring.application.name=beatland

#"Datenbank heiﬂt beatland, sie l‰uft auf Port 5432 (Standard PostgresSQL Port), verbinde dich damit"

spring.datasource.url=jdbc:postgresql://localhost:5432/beatland
spring.datasource.username=leonardobostan
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update